go_to_location:
  - {name: "ur5_home",   frame: "world", position: [0.705, -0.374, 1.299], quaternion: [0.685,  0.728, 0.015, -0.009]}
  - {name: "ur5_away",   frame: "world", position: [1.299, -0.350, 1.422], quaternion: [0.652,  0.726, 0.028, -0.218]}
# Home for scaling
  # - {name: "ur5_home",   frame: "world", position: [2.057, -0.292, 1.312], quaternion: [0.685, 0.728, 0.015, -0.009]}

  - {name: "human_home", frame: "world", position: [0.437, 1.499, 1.158], quaternion: [-0.493, -0.430, 0.616, -0.439]}
  - {name: "human_away", frame: "world", position: [0.446, 1.921, 1.154], quaternion: [-0.493, -0.430, 0.616, -0.439]}
