inbound:
  boxes:
  - {name: "human_desk",    frame: "tabletop",         position: [0, 0, 0.2],         quaternion: [1, 0, 0, 0], heigth: 0.1} # vettore
  - {name: "robot_desk1",    frame: "shopdesk",        position: [ 0.24, 0.33, 0.05], quaternion: [1, 0, 0, 0], heigth: 0.1}
  - {name: "robot_desk2",    frame: "shopdesk",        position: [ 0.24, 0.27, 0.05], quaternion: [1, 0, 0, 0], heigth: 0.1}
  - {name: "robot_desk3",    frame: "shopdesk",        position: [ 0.24, 0.33, 0.05], quaternion: [1, 0, 0, 0], heigth: 0.1}
  - {name: "robot_desk4",    frame: "shopdesk",        position: [-0.24, 0.27, 0.05], quaternion: [1, 0, 0, 0], heigth: 0.1}
  - {name: "common_desk1",   frame: "conveyor_system", position: [ 2.14, 0.22 ,0.05], quaternion: [1, 0, 0, 0], heigth: 0.1}
  - {name: "common_desk2",   frame: "conveyor_system", position: [ 1.60, 0.22 ,0.05], quaternion: [1, 0, 0, 0], heigth: 0.1}
  - {name: "common_desk3",   frame: "conveyor_system", position: [ 2.38, 0.22 ,0.05], quaternion: [1, 0, 0, 0], heigth: 0.1}
  - {name: "common_desk4",   frame: "conveyor_system", position: [ 1.90, 0.22 ,0.05], quaternion: [1, 0, 0, 0], heigth: 0.1}

inbound_pick_server:
  groups:
    ur5_on_guide: tip
    human_right_arm: RightTip

  request_adapters:
  - default_planner_request_adapters/AddTimeParameterization
  - default_planner_request_adapters/FixWorkspaceBounds
  - default_planner_request_adapters/FixStartStateBounds
  - default_planner_request_adapters/FixStartStateCollision
  - default_planner_request_adapters/FixStartStatePathConstraints
