multi_skills:
  group_name:
  - "ur5_on_guide"
  - "human_right_arm"

  recipes:
  - {name: "first_recipe", recipe: ["go_to_ur5_home","pick_orange_box","place_A1","go_to_ur5_home"]}
  - {name: "second_recipe", recipe: ["go_to_human_home","pick_white_box","place_white_box","go_to_human_home"]}

  tasks:
  - {name: "go_to_ur5_home",   type: "goto",  description: "", agent: ["ur5_on_guide"],                 goal: ["ur5_home"]}
  - {name: "go_to_ur5_away",   type: "goto",  description: "", agent: ["ur5_on_guide"],                 goal: ["ur5_away"]}
  - {name: "go_to_human_home", type: "goto",  description: "", agent: ["human_right_arm"],              goal: ["human_home"]}
  - {name: "go_to_human_away", type: "goto",  description: "", agent: ["human_right_arm"],              goal: ["human_away"]}
  - {name: "pick_white_box",   type: "pick",  description: "", agent: ["human_right_arm"],              goal: ["white_box"]}
  - {name: "pick_orange_box",  type: "pick",  description: "", agent: ["ur5_on_guide"],                 goal: ["orange_box"]}
  - {name: "pick_blue_box",    type: "pick",  description: "", agent: ["human_right_arm,ur5_on_guide"], goal: ["blue_box"]}
  - {name: "place_A1",         type: "place", description: "", agent: ["ur5_on_guide"],                 goal: ["A1_group"]}
  - {name: "place_A2",         type: "place", description: "", agent: ["ur5_on_guide"],                 goal: ["A2_group"]}
  - {name: "place_A3",         type: "place", description: "", agent: ["ur5_on_guide"],                 goal: ["A3_group"]}
  - {name: "place_A4",         type: "place", description: "", agent: ["ur5_on_guide"],                 goal: ["A4_group"]}
  - {name: "place_A5",         type: "place", description: "", agent: ["ur5_on_guide"],                 goal: ["A5_group"]}
  - {name: "place_B1",         type: "place", description: "", agent: ["ur5_on_guide"],                 goal: ["B1_group"]}
  - {name: "place_B2",         type: "place", description: "", agent: ["ur5_on_guide"],                 goal: ["B2_group"]}
  - {name: "place_B3",         type: "place", description: "", agent: ["ur5_on_guide"],                 goal: ["B3_group"]}
  - {name: "place_B4",         type: "place", description: "", agent: ["ur5_on_guide"],                 goal: ["B4_group"]}
  - {name: "place_B5",         type: "place", description: "", agent: ["ur5_on_guide"],                 goal: ["B5_group"]}
  - {name: "place_C1",         type: "place", description: "", agent: ["ur5_on_guide"],                 goal: ["C1_group"]}
  - {name: "place_C2",         type: "place", description: "", agent: ["ur5_on_guide"],                 goal: ["C2_group"]}
  - {name: "place_C3",         type: "place", description: "", agent: ["ur5_on_guide"],                 goal: ["C3_group"]}
  - {name: "place_C4",         type: "place", description: "", agent: ["ur5_on_guide"],                 goal: ["C4_group"]}
  - {name: "place_C5",         type: "place", description: "", agent: ["ur5_on_guide"],                 goal: ["C5_group"]}
  - {name: "place_D1",         type: "place", description: "", agent: ["ur5_on_guide"],                 goal: ["D1_group"]}
  - {name: "place_D2",         type: "place", description: "", agent: ["ur5_on_guide"],                 goal: ["D2_group"]}
  - {name: "place_D3",         type: "place", description: "", agent: ["ur5_on_guide"],                 goal: ["D3_group"]}
  - {name: "place_D4",         type: "place", description: "", agent: ["ur5_on_guide"],                 goal: ["D4_group"]}
  - {name: "place_D5",         type: "place", description: "", agent: ["ur5_on_guide"],                 goal: ["D5_group"]}
  - {name: "place_J1",         type: "place", description: "", agent: ["human_right_arm"],              goal: ["J1_group"]}
  - {name: "place_J2",         type: "place", description: "", agent: ["human_right_arm"],              goal: ["J2_group"]}
  - {name: "place_J3",         type: "place", description: "", agent: ["human_right_arm"],              goal: ["J3_group"]}
  - {name: "place_J4",         type: "place", description: "", agent: ["human_right_arm"],              goal: ["J4_group"]}
  - {name: "place_J5",         type: "place", description: "", agent: ["human_right_arm"],              goal: ["J5_group"]}
  - {name: "place_I1",         type: "place", description: "", agent: ["human_right_arm"],              goal: ["I1_group"]}
  - {name: "place_I2",         type: "place", description: "", agent: ["human_right_arm"],              goal: ["I2_group"]}
  - {name: "place_I3",         type: "place", description: "", agent: ["human_right_arm"],              goal: ["I3_group"]}
  - {name: "place_I4",         type: "place", description: "", agent: ["human_right_arm"],              goal: ["I4_group"]}
  - {name: "place_I5",         type: "place", description: "", agent: ["human_right_arm"],              goal: ["I5_group"]}
  - {name: "place_H1",         type: "place", description: "", agent: ["human_right_arm"],              goal: ["H1_group"]}
  - {name: "place_H2",         type: "place", description: "", agent: ["human_right_arm"],              goal: ["H2_group"]}
  - {name: "place_H3",         type: "place", description: "", agent: ["human_right_arm"],              goal: ["H3_group"]}
  - {name: "place_H4",         type: "place", description: "", agent: ["human_right_arm"],              goal: ["H4_group"]}
  - {name: "place_H5",         type: "place", description: "", agent: ["human_right_arm"],              goal: ["H5_group"]}
  - {name: "place_G1",         type: "place", description: "", agent: ["human_right_arm"],              goal: ["G1_group"]}
  - {name: "place_G2",         type: "place", description: "", agent: ["human_right_arm"],              goal: ["G2_group"]}
  - {name: "place_G3",         type: "place", description: "", agent: ["human_right_arm"],              goal: ["G3_group"]}
  - {name: "place_G4",         type: "place", description: "", agent: ["human_right_arm"],              goal: ["G4_group"]}
  - {name: "place_G5",         type: "place", description: "", agent: ["human_right_arm"],              goal: ["G5_group"]}
  - {name: "place_F1",         type: "place", description: "", agent: ["human_right_arm"],              goal: ["F1_group"]}
  - {name: "place_F2",         type: "place", description: "", agent: ["human_right_arm"],              goal: ["F2_group"]}
  - {name: "place_F3",         type: "place", description: "", agent: ["human_right_arm"],              goal: ["F3_group"]}
  - {name: "place_F4",         type: "place", description: "", agent: ["human_right_arm"],              goal: ["F4_group"]}
  - {name: "place_F5",         type: "place", description: "", agent: ["human_right_arm"],              goal: ["F5_group"]}
  - {name: "place_E1",         type: "place", description: "", agent: ["human_right_arm"],              goal: ["E1_group"]}
  - {name: "place_E2",         type: "place", description: "", agent: ["human_right_arm"],              goal: ["E2_group"]}
  - {name: "place_E3",         type: "place", description: "", agent: ["human_right_arm"],              goal: ["E3_group"]}
  - {name: "place_E4",         type: "place", description: "", agent: ["human_right_arm"],              goal: ["E4_group"]}
  - {name: "place_E5",         type: "place", description: "", agent: ["human_right_arm"],              goal: ["E5_group"]}
















































