object_geometries:

  white_box:
   box: [0.05, 0.05, 0.05]
   color: [1,1,1,1.]
   offset: [0,0,-0.025] #


  orange_box:
    box: [0.05, 0.05, 0.05]
    color: [1,0.8,0,1.]
    offset: [0,0,-0.025]

  blue_box:
    box: [0.05, 0.05, 0.05]
    color: [0.2,0.3,0.7,1.0]
    offset: [0,0,-0.025]

  white_box_0:
    box: [0.05, 0.05, 0.05]
    color: [1,1,1,1.]
    offset: [0,0,-0.025]

  white_box_1:
    box: [0.05, 0.05, 0.05]
    color: [1,1,1,1.]
    offset: [0,0,-0.025]

  white_box_2:
    box: [0.05, 0.05, 0.05]
    color: [1,1,1,1.]
    offset: [0,0,-0.025]

  white_box_3:
    box: [0.05, 0.05, 0.05]
    color: [1,1,1,1.]
    offset: [0,0,-0.025]

  white_box_4:
    box: [0.05, 0.05, 0.05]
    color: [1,1,1,1.]
    offset: [0,0,-0.025]

  white_box_5:
    box: [0.05, 0.05, 0.05]
    color: [1,1,1,1.]
    offset: [0,0,-0.025]

  white_box_6:
    box: [0.05, 0.05, 0.05]
    color: [1,1,1,1.]
    offset: [0,0,-0.025]

  white_box_7:
    box: [0.05, 0.05, 0.05]
    color: [1,1,1,1.]
    offset: [0,0,-0.025]

  white_box_8:
    box: [0.05, 0.05, 0.05]
    color: [1,1,1,1.]
    offset: [0,0,-0.025]

  white_box_9:
    box: [0.05, 0.05, 0.05]
    color: [1,1,1,1.]
    offset: [0,0,-0.025]

  white_box_10:
    box: [0.05, 0.05, 0.05]
    color: [1,1,1,1.]
    offset: [0,0,-0.025]

  white_box_11:
    box: [0.05, 0.05, 0.05]
    color: [1,1,1,1.]
    offset: [0,0,-0.025]

  white_box_12:
    box: [0.05, 0.05, 0.05]
    color: [1,1,1,1.]
    offset: [0,0,-0.025]

  white_box_13:
    box: [0.05, 0.05, 0.05]
    color: [1,1,1,1.]
    offset: [0,0,-0.025]

  white_box_14:
    box: [0.05, 0.05, 0.05]
    color: [1,1,1,1.]
    offset: [0,0,-0.025]

  orange_box_0:
    box: [0.05, 0.05, 0.05]
    color: [1,0.8,0,1.]
    offset: [0,0,-0.025]

  orange_box_1:
    box: [0.05, 0.05, 0.05]
    color: [1,0.8,0,1.]
    offset: [0,0,-0.025]

  orange_box_2:
    box: [0.05, 0.05, 0.05]
    color: [1,0.8,0,1.]
    offset: [0,0,-0.025]

  orange_box_3:
    box: [0.05, 0.05, 0.05]
    color: [1,0.8,0,1.]
    offset: [0,0,-0.025]

  orange_box_4:
    box: [0.05, 0.05, 0.05]
    color: [1,0.8,0,1.]
    offset: [0,0,-0.025]

  orange_box_5:
    box: [0.05, 0.05, 0.05]
    color: [1,0.8,0,1.]
    offset: [0,0,-0.025]

  orange_box_6:
    box: [0.05, 0.05, 0.05]
    color: [1,0.8,0,1.]
    offset: [0,0,-0.025]

  orange_box_7:
    box: [0.05, 0.05, 0.05]
    color: [1,0.8,0,1.]
    offset: [0,0,-0.025]

  orange_box_8:
    box: [0.05, 0.05, 0.05]
    color: [1,0.8,0,1.]
    offset: [0,0,-0.025]

  orange_box_9:
    box: [0.05, 0.05, 0.05]
    color: [1,0.8,0,1.]
    offset: [0,0,-0.025]

  orange_box_10:
    box: [0.05, 0.05, 0.05]
    color: [1,0.8,0,1.]
    offset: [0,0,-0.025]

  orange_box_11:
    box: [0.05, 0.05, 0.05]
    color: [1,0.8,0,1.]
    offset: [0,0,-0.025]

  orange_box_12:
    box: [0.05, 0.05, 0.05]
    color: [1,0.8,0,1.]
    offset: [0,0,-0.025]

  orange_box_13:
    box: [0.05, 0.05, 0.05]
    color: [1,0.8,0,1.]
    offset: [0,0,-0.025]

  blue_box_0:
    box: [0.05, 0.05, 0.05]
    color: [0.2,0.3,0.7,1.0]
    offset: [0,0,-0.025]

  blue_box_1:
    box: [0.05, 0.05, 0.05]
    color: [0.2,0.3,0.7,1.0]
    offset: [0,0,-0.025]

  blue_box_2:
    box: [0.05, 0.05, 0.05]
    color: [0.2,0.3,0.7,1.0]
    offset: [0,0,-0.025]

  blue_box_3:
    box: [0.05, 0.05, 0.05]
    color: [0.2,0.3,0.7,1.0]
    offset: [0,0,-0.025]

  blue_box_4:
    box: [0.05, 0.05, 0.05]
    color: [0.2,0.3,0.7,1.0]
    offset: [0,0,-0.025]

  blue_box_5:
    box: [0.05, 0.05, 0.05]
    color: [0.2,0.3,0.7,1.0]
    offset: [0,0,-0.025]

  blue_box_6:
    box: [0.05, 0.05, 0.05]
    color: [0.2,0.3,0.7,1.0]
    offset: [0,0,-0.025]

  blue_box_7:
    box: [0.05, 0.05, 0.05]
    color: [0.2,0.3,0.7,1.0]
    offset: [0,0,-0.025]

  blue_box_8:
    box: [0.05, 0.05, 0.05]
    color: [0.2,0.3,0.7,1.0]
    offset: [0,0,-0.025]

  blue_box_9:
    box: [0.05, 0.05, 0.05]
    color: [0.2,0.3,0.7,1.0]
    offset: [0,0,-0.025]

  blue_box_10:
    box: [0.05, 0.05, 0.05]
    color: [0.2,0.3,0.7,1.0]
    offset: [0,0,-0.025]

  blue_box_11:
    box: [0.05, 0.05, 0.05]
    color: [0.2,0.3,0.7,1.0]
    offset: [0,0,-0.025]

  blue_box_12:
    box: [0.05, 0.05, 0.05]
    color: [0.2,0.3,0.7,1.0]
    offset: [0,0,-0.025]

  blue_box_13:
    box: [0.05, 0.05, 0.05]
    color: [0.2,0.3,0.7,1.0]
    offset: [0,0,-0.025]

  blue_box_14:
    box: [0.05, 0.05, 0.05]
    color: [0.2,0.3,0.7,1.0]
    offset: [0,0,-0.025]

  blue_box_15:
    box: [0.05, 0.05, 0.05]
    color: [0.2,0.3,0.7,1.0]
    offset: [0,0,-0.025]

  blue_box_16:
    box: [0.05, 0.05, 0.05]
    color: [0.2,0.3,0.7,1.0]
    offset: [0,0,-0.025]

  blue_box_17:
    box: [0.05, 0.05, 0.05]
    color: [0.2,0.3,0.7,1.0]
    offset: [0,0,-0.025]

  blue_box_18:
    box: [0.05, 0.05, 0.05]
    color: [0.2,0.3,0.7,1.0]
    offset: [0,0,-0.025]

  blue_box_19:
    box: [0.05, 0.05, 0.05]
    color: [0.2,0.3,0.7,1.0]
    offset: [0,0,-0.025]

  blue_box_20:
    box: [0.05, 0.05, 0.05]
    color: [0.2,0.3,0.7,1.0]
    offset: [0,0,-0.025]

  blue_box_21:
    box: [0.05, 0.05, 0.05]
    color: [0.2,0.3,0.7,1.0]
    offset: [0,0,-0.025]

  blue_box_22:
    box: [0.05, 0.05, 0.05]
    color: [0.2,0.3,0.7,1.0]
    offset: [0,0,-0.025]

  blue_box_23:
    box: [0.05, 0.05, 0.05]
    color: [0.2,0.3,0.7,1.0]
    offset: [0,0,-0.025]

  blue_box_24:
    box: [0.05, 0.05, 0.05]
    color: [0.2,0.3,0.7,1.0]
    offset: [0,0,-0.025]

  blue_box_25:
    box: [0.05, 0.05, 0.05]
    color: [0.2,0.3,0.7,1.0]
    offset: [0,0,-0.025]

  blue_box_26:
    box: [0.05, 0.05, 0.05]
    color: [0.2,0.3,0.7,1.0]
    offset: [0,0,-0.025]
