outbound_mosaic:
  frame: "conveyor_system"
  group_names:
  - ur5_on_guide
  - human_right_arm
  slots:
  - {name: "A1", position: [1.54, 0.10, 0.05], quaternion: [1, 0, 0, 0], approach_distance: [0, 0, 0.07]}
  - {name: "A2", position: [1.54, 0.16, 0.05], quaternion: [1, 0, 0, 0], approach_distance: [0, 0, 0.07]}
  - {name: "A3", position: [1.54, 0.22, 0.05], quaternion: [1, 0, 0, 0], approach_distance: [0, 0, 0.07]}
  - {name: "A4", position: [1.54, 0.28, 0.05], quaternion: [1, 0, 0, 0], approach_distance: [0, 0, 0.07]}
  - {name: "A5", position: [1.54, 0.34, 0.05], quaternion: [1, 0, 0, 0], approach_distance: [0, 0, 0.07]}
  - {name: "B1", position: [1.48, 0.10, 0.05], quaternion: [1, 0, 0, 0], approach_distance: [0, 0, 0.07]}
  - {name: "B2", position: [1.48, 0.16, 0.05], quaternion: [1, 0, 0, 0], approach_distance: [0, 0, 0.07]}
  - {name: "B3", position: [1.48, 0.22, 0.05], quaternion: [1, 0, 0, 0], approach_distance: [0, 0, 0.07]}
  - {name: "B4", position: [1.48, 0.28, 0.05], quaternion: [1, 0, 0, 0], approach_distance: [0, 0, 0.07]}
  - {name: "B5", position: [1.48, 0.34, 0.05], quaternion: [1, 0, 0, 0], approach_distance: [0, 0, 0.07]}
  - {name: "C1", position: [1.42, 0.10, 0.05], quaternion: [1, 0, 0, 0], approach_distance: [0, 0, 0.07]}
  - {name: "C2", position: [1.42, 0.16, 0.05], quaternion: [1, 0, 0, 0], approach_distance: [0, 0, 0.07]}
  - {name: "C3", position: [1.42, 0.22, 0.05], quaternion: [1, 0, 0, 0], approach_distance: [0, 0, 0.07]}
  - {name: "C4", position: [1.42, 0.28, 0.05], quaternion: [1, 0, 0, 0], approach_distance: [0, 0, 0.07]}
  - {name: "C5", position: [1.42, 0.34, 0.05], quaternion: [1, 0, 0, 0], approach_distance: [0, 0, 0.07]}
  - {name: "D1", position: [1.36, 0.10, 0.05], quaternion: [1, 0, 0, 0], approach_distance: [0, 0, 0.07]}
  - {name: "D2", position: [1.36, 0.16, 0.05], quaternion: [1, 0, 0, 0], approach_distance: [0, 0, 0.07]}
  - {name: "D3", position: [1.36, 0.22, 0.05], quaternion: [1, 0, 0, 0], approach_distance: [0, 0, 0.07]}
  - {name: "D4", position: [1.36, 0.28, 0.05], quaternion: [1, 0, 0, 0], approach_distance: [0, 0, 0.07]}
  - {name: "D5", position: [1.36, 0.34, 0.05], quaternion: [1, 0, 0, 0], approach_distance: [0, 0, 0.07]}
  - {name: "E1", position: [1.30, 0.10, 0.05], quaternion: [1, 0, 0, 0], approach_distance: [0, 0, 0.07]}
  - {name: "E2", position: [1.30, 0.16, 0.05], quaternion: [1, 0, 0, 0], approach_distance: [0, 0, 0.07]}
  - {name: "E3", position: [1.30, 0.22, 0.05], quaternion: [1, 0, 0, 0], approach_distance: [0, 0, 0.07]}
  - {name: "E4", position: [1.30, 0.28, 0.05], quaternion: [1, 0, 0, 0], approach_distance: [0, 0, 0.07]}
  - {name: "E5", position: [1.30, 0.34, 0.05], quaternion: [1, 0, 0, 0], approach_distance: [0, 0, 0.07]}
  - {name: "F1", position: [1.24, 0.10, 0.05], quaternion: [1, 0, 0, 0], approach_distance: [0, 0, 0.07]}
  - {name: "F2", position: [1.24, 0.16, 0.05], quaternion: [1, 0, 0, 0], approach_distance: [0, 0, 0.07]}
  - {name: "F3", position: [1.24, 0.22, 0.05], quaternion: [1, 0, 0, 0], approach_distance: [0, 0, 0.07]}
  - {name: "F4", position: [1.24, 0.28, 0.05], quaternion: [1, 0, 0, 0], approach_distance: [0, 0, 0.07]}
  - {name: "F5", position: [1.24, 0.34, 0.05], quaternion: [1, 0, 0, 0], approach_distance: [0, 0, 0.07]}
  - {name: "G1", position: [1.18, 0.10, 0.05], quaternion: [1, 0, 0, 0], approach_distance: [0, 0, 0.07]}
  - {name: "G2", position: [1.18, 0.16, 0.05], quaternion: [1, 0, 0, 0], approach_distance: [0, 0, 0.07]}
  - {name: "G3", position: [1.18, 0.22, 0.05], quaternion: [1, 0, 0, 0], approach_distance: [0, 0, 0.07]}
  - {name: "G4", position: [1.18, 0.28, 0.05], quaternion: [1, 0, 0, 0], approach_distance: [0, 0, 0.07]}
  - {name: "G5", position: [1.18, 0.34, 0.05], quaternion: [1, 0, 0, 0], approach_distance: [0, 0, 0.07]}
  - {name: "H1", position: [1.12, 0.10, 0.05], quaternion: [1, 0, 0, 0], approach_distance: [0, 0, 0.07]}
  - {name: "H2", position: [1.12, 0.16, 0.05], quaternion: [1, 0, 0, 0], approach_distance: [0, 0, 0.07]}
  - {name: "H3", position: [1.12, 0.22, 0.05], quaternion: [1, 0, 0, 0], approach_distance: [0, 0, 0.07]}
  - {name: "H4", position: [1.12, 0.28, 0.05], quaternion: [1, 0, 0, 0], approach_distance: [0, 0, 0.07]}
  - {name: "H5", position: [1.12, 0.34, 0.05], quaternion: [1, 0, 0, 0], approach_distance: [0, 0, 0.07]}
  - {name: "I1", position: [1.06, 0.10, 0.05], quaternion: [1, 0, 0, 0], approach_distance: [0, 0, 0.07]}
  - {name: "I2", position: [1.06, 0.16, 0.05], quaternion: [1, 0, 0, 0], approach_distance: [0, 0, 0.07]}
  - {name: "I3", position: [1.06, 0.22, 0.05], quaternion: [1, 0, 0, 0], approach_distance: [0, 0, 0.07]}
  - {name: "I4", position: [1.06, 0.28, 0.05], quaternion: [1, 0, 0, 0], approach_distance: [0, 0, 0.07]}
  - {name: "I5", position: [1.06, 0.34, 0.05], quaternion: [1, 0, 0, 0], approach_distance: [0, 0, 0.07]}
  - {name: "J1", position: [1.00, 0.10, 0.05], quaternion: [1, 0, 0, 0], approach_distance: [0, 0, 0.07]}
  - {name: "J2", position: [1.00, 0.16, 0.05], quaternion: [1, 0, 0, 0], approach_distance: [0, 0, 0.07]}
  - {name: "J3", position: [1.00, 0.22, 0.05], quaternion: [1, 0, 0, 0], approach_distance: [0, 0, 0.07]}
  - {name: "J4", position: [1.00, 0.28, 0.05], quaternion: [1, 0, 0, 0], approach_distance: [0, 0, 0.07]}
  - {name: "J5", position: [1.00, 0.34, 0.05], quaternion: [1, 0, 0, 0], approach_distance: [0, 0, 0.07]}

  request_adapters:
  - default_planner_request_adapters/AddTimeParameterization
  - default_planner_request_adapters/FixWorkspaceBounds
  - default_planner_request_adapters/FixStartStateBounds
  - default_planner_request_adapters/FixStartStateCollision
  - default_planner_request_adapters/FixStartStatePathConstraints




