human:
  group_name: "human_right_arm"
  recipe:
    A1: "white_box"
    A2: "blue_box"
    B1: "white_box"
    B2: "blue_box"
    C1: "white_box"
    C2: "white_box"
    C3: "blue_box"
    C4: "blue_box"


robot:
  group_name: "ur5_on_guide"
  recipe:
    A3: "orange_box"
    A4: "blue_box"
    A5: "blue_box"
    B3: "orange_box"
    B4: "blue_box"
    B5: "orange_box"
    C5: "blue_box"


